// <auto-generated />
using System;
using BookManagementSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace BookManagementSystem.Data.Migrations
{
    [DbContext(typeof(BookManagementSystemContext))]
    partial class BookManagementSystemContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("BookManagementSystem.Data.Model.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnName("AUTHORNAME")
                        .HasColumnType("VARCHAR2(40)");

                    b.Property<int?>("BookId");

                    b.Property<bool>("IsDeleted");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("AUTHOR");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Ivan Vazov",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Peio Qvorov",
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Dimcho Debelqnov",
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("BookManagementSystem.Data.Model.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("BookTitle")
                        .IsRequired()
                        .HasColumnName("BOOKTITLE")
                        .HasColumnType("VARCHAR2(50)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnName("DATECREATED")
                        .HasColumnType("DATE");

                    b.Property<bool>("IsDeleted");

                    b.HasKey("Id");

                    b.ToTable("BOOK");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BookTitle = "Pod Igoto",
                            DateCreated = new DateTime(2014, 4, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2,
                            BookTitle = "Poeziq",
                            DateCreated = new DateTime(2020, 2, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3,
                            BookTitle = "V polite na Vitosha",
                            DateCreated = new DateTime(2018, 6, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("BookManagementSystem.Data.Model.Author", b =>
                {
                    b.HasOne("BookManagementSystem.Data.Model.Book", "Book")
                        .WithMany("Authors")
                        .HasForeignKey("BookId");
                });
#pragma warning restore 612, 618
        }
    }
}
